# Generated by Django 3.1.1 on 2020-11-21 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='/static/microdollars/missing.png', upload_to='myimages')),
                ('about_me', models.TextField(default='INFO ON THIS ORGANIZATION', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_search', models.CharField(default=' ', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=350)),
                ('donateto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microdollars.organizationmodel', verbose_name='Organization')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
