# Generated by Django 3.1.1 on 2020-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='user_search',
            field=models.CharField(default='', max_length=350),
        ),
    ]
